<template>
  <div>
    <TopBar :menuClick="menuClick"></TopBar>
    <Home></Home>
    <transition name="fade">
    <Menu v-show="showMenu"></Menu>
    </transition>
  </div>
</template>

<script>
import Home from './components/Home.vue'
import Menu from './components/Menu.vue'
import TopBar from './components/TopBar.vue'

export default {
  name: 'App',
  components: {
    Home,
    Menu,
    TopBar

  },
  data () {
      return {
          showMenu: false
      }
  },
  methods: {
    menuClick () {
      this.showMenu = !this.showMenu;
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  display: flex;
  flex-direction: column;
  align-content: center;
  align-items: center;
  justify-content: center;
  height: 100%
}

.fade-enter-active {
	-webkit-animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	animation: fade-in 0.7s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

.fade-leave-active {
    animation: fade-in 0.7s cubic-bezier(1, 0.565, 0.575, 0.390) both reverse;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-5-10 19:13:35
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-out
 * ----------------------------------------
 */

@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

</style>
